Implement user sessions
kthchew/CatCorp pull request #14
Opened 2024-03-03 22:02 UTC by kthchew

Introduce user sessions - now you won't get logged out on refresh

- New endpoint: `/logout` - destroys current session
- New endpoint: `/getAccountInfo` - for if you're already logged in (should `/login`'s similar logic be removed from there?)
- All endpoints now check the session cookie for the Canvas API key, user IDs instead of looking in the body/query
- Refactoring: several functions moved into new `user.js` file that do actions based on the provided session

To do:
- [ ] review CORS settings
- [ ] may want to wait for other PRs to merge first

2024-03-08 20:25 UTC, MaximilianMeiler requested changes

2024-03-08 20:25 UTC, MaximilianMeiler commented on Backend/server.js
> +
make sure ALL of the login's functions are replicated here (ex. cashing in submissions)

2024-03-10 05:14 UTC, kthchew commented
Known issues:

- The login UI does not show any indicator if there is a current session and it is currently trying to login
- Cashing submissions twice in quick succession can cause the user to earn duplicate gems. We should lock this function so it can only run once per user at a time and not multiple times simultaneously. This is a bit complicated and not really within the topic of this PR (which is already getting a bit larger than I intended) so I'd like to solve it in a separate PR

2024-03-18 19:33 UTC, MaximilianMeiler commented
ENVs in Vite need to use a VITE_ prefix (i think)

2024-03-18 19:40 UTC, merged