Status descriptions on login
kthchew/CatCorp pull request #16
Opened 2024-03-04 19:50 UTC by MaximilianMeiler

May need a css revamp...just like the entire rest of the login page

2024-03-04 20:06 UTC, kthchew requested changes
cool

2024-03-04 20:06 UTC, kthchew commented on Frontend/src/Login.jsx
> +        setLoginResponse(e.response.data.message);
this doesn't check if there's actually a response (a backend that is down or times out will cause the front end to simply stall on logging in forever)

2024-03-04 20:33 UTC, MaximilianMeiler reviewed
@kthchew Can you attempt to continue this fix? I think you're more familiar with the backend's error structure than I am

2024-03-05 06:40 UTC, kthchew commented
@MaximilianMeiler I think this should fix it. I changed the errors from `canvas.js` so they should contain a recommended status code as well to make things easier. I haven't been able to trigger the rate limit but I tried invalid API keys and they didn't crash the server.

For reference, essentially any exported function in `canvas.js` (that contacts the Canvas API) can throw. It needs to be caught when used like so:

```js
try {
  const user = await canvas.getUser(canvas_api_token);
  return res.json(user);
} catch (error) {
  return res.status(error.status).json({ error: error.message });
}
```

2024-03-08 20:12 UTC, kthchew approved these changes
lgtm

2024-03-08 20:12 UTC, merged