​
kthchew/CatCorp pull request #40
Opened 2024-04-03 20:23 UTC by kthchew

​

2024-04-03 20:25 UTC, MonsieurMantis commented
fails the unit tests. denied

2024-04-03 20:25 UTC, MonsieurMantis requested changes
Needs to pass unit tests

2024-04-03 20:27 UTC, MonsieurMantis approved these changes
LGTM (Let's Get This Money)

2024-04-10 20:42 UTC, kthchew commented
My lawyer has advised me not to merge this PR

2024-04-10 20:42 UTC, closed without merging